/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Log } from "./interfaces/log";
import { Language } from "./interfaces/translation";
import { BackDropOptions, OptionConfig } from "./interfaces/options";
import { FoliageRatio } from "./components/fruit-tree/fruit";
import { Nullable } from "./interfaces/geneneral-types";
import { Player } from "./facade/character";
import { SkeletonType } from "./components/skeleton-loader/skeleton-loader";
export { Log } from "./interfaces/log";
export { Language } from "./interfaces/translation";
export { BackDropOptions, OptionConfig } from "./interfaces/options";
export { FoliageRatio } from "./components/fruit-tree/fruit";
export { Nullable } from "./interfaces/geneneral-types";
export { Player } from "./facade/character";
export { SkeletonType } from "./components/skeleton-loader/skeleton-loader";
export namespace Components {
    interface AppHome {
    }
    /**
     * -  TODO aria
     * -  TODO first page + 404page links to back & home
     * -  TODO modals :  Upcoming features
     * -  TODO translate: FR, ES, EN, HT
     * - TODO settings menu : Language , resolution, FPS ...
     * - TODO Test new fonts:  Monument Grotesk
     * - TODO Add sound in open and close menu, change link...
     * - TODO Add my picture+ name
     */
    interface AppRoot {
    }
    interface BackgroundActivity {
        /**
          * @default ''
         */
        "digiCode": string;
        "menuWidth": number;
    }
    interface CharacterSelection {
    }
    interface ConsoleAbout {
    }
    interface ConsoleWelcome {
    }
    interface DropdownButton {
        /**
          * @default {}
         */
        "options": Partial<OptionConfig>;
    }
    interface FruitItem {
        /**
          * @default false
         */
        "crystal": boolean;
        /**
          * @default 0
         */
        "flavor": number;
        /**
          * @default 0
         */
        "type": number;
    }
    interface FruitTree {
        /**
          * @default false
         */
        "debug": boolean;
        /**
          * @default 'inherit'
         */
        "filter": string;
        /**
          * @default 0
         */
        "fruit": number;
        /**
          * @default 16
         */
        "fruitSize": number;
        /**
          * @default '../../assets/images/tree.png'
         */
        "image": string;
        /**
          * @default 8
         */
        "numberOfFruits": number;
        /**
          * @default DEFAULT_FOLIAGE_RATIOS
         */
        "ratios": FoliageRatio;
        /**
          * @default 1
         */
        "scale": number;
        /**
          * @default 'inherit'
         */
        "transform": string;
    }
    interface Gui404 {
    }
    interface GuiAbout {
        "hash": string | undefined;
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface GuiBlog {
        "hash": string;
        /**
          * @default true
         */
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface GuiProjects {
        "hash": string;
        /**
          * @default true
         */
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface GuiWelcome {
        "menuOpened": boolean;
        "menuWidth": number;
        "player": Nullable<Player>;
    }
    interface LanguageSelector {
    }
    interface LoadingModal {
        "player"?: Nullable<Player>;
        "progress": number;
        "progressText": string;
        "volumeMuted": boolean;
    }
    interface LogoText {
    }
    interface MainFooter {
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface MainHeader {
        "menuOpened": boolean;
        "menuWidth": number;
        "message"?: {
    text?: string;
    content?: string
  };
        "player"?: Nullable<Player>;
        "volumeMuted": boolean;
    }
    interface MessageBubble {
        "character": Nullable<HTMLElement>;
        "message"?: string;
    }
    interface ModalBackdrop {
    }
    interface PageNotFound {
    }
    interface PwaInstallPrompt {
    }
    interface RightPanel {
        "isOpened"?: boolean;
    }
    interface SimpleLink {
        /**
          * @default 'FruitsBytes'
         */
        "label": string;
        /**
          * @default '/welcome#'
         */
        "link": string;
        /**
          * @default {}
         */
        "state": Object;
    }
    interface SkeletonLoader {
        /**
          * @default true
         */
        "animated": boolean;
        /**
          * @default 1
         */
        "count": number;
        /**
          * @default '20px'
         */
        "height": string;
        /**
          * @default 'text'
         */
        "type": SkeletonType;
        /**
          * @default '100%'
         */
        "width": string;
    }
    interface SocialLinks {
    }
}
export interface AppRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppRootElement;
}
export interface CharacterSelectionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCharacterSelectionElement;
}
export interface ConsoleAboutCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLConsoleAboutElement;
}
export interface Gui404CustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGui404Element;
}
export interface GuiWelcomeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGuiWelcomeElement;
}
export interface LoadingModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLoadingModalElement;
}
export interface MainHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMainHeaderElement;
}
export interface ModalBackdropCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalBackdropElement;
}
export interface RightPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRightPanelElement;
}
export interface SimpleLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSimpleLinkElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElementEventMap {
        "state.pushed": { state: any; title: string; url?: string | URL | null; };
        "console.logged": Log;
        "redraw.screen": boolean;
        "language.changed": Language;
    }
    /**
     * -  TODO aria
     * -  TODO first page + 404page links to back & home
     * -  TODO modals :  Upcoming features
     * -  TODO translate: FR, ES, EN, HT
     * - TODO settings menu : Language , resolution, FPS ...
     * - TODO Test new fonts:  Monument Grotesk
     * - TODO Add sound in open and close menu, change link...
     * - TODO Add my picture+ name
     */
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppRootElementEventMap>(type: K, listener: (this: HTMLAppRootElement, ev: AppRootCustomEvent<HTMLAppRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppRootElementEventMap>(type: K, listener: (this: HTMLAppRootElement, ev: AppRootCustomEvent<HTMLAppRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBackgroundActivityElement extends Components.BackgroundActivity, HTMLStencilElement {
    }
    var HTMLBackgroundActivityElement: {
        prototype: HTMLBackgroundActivityElement;
        new (): HTMLBackgroundActivityElement;
    };
    interface HTMLCharacterSelectionElementEventMap {
        "close.loading": boolean;
    }
    interface HTMLCharacterSelectionElement extends Components.CharacterSelection, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCharacterSelectionElementEventMap>(type: K, listener: (this: HTMLCharacterSelectionElement, ev: CharacterSelectionCustomEvent<HTMLCharacterSelectionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCharacterSelectionElementEventMap>(type: K, listener: (this: HTMLCharacterSelectionElement, ev: CharacterSelectionCustomEvent<HTMLCharacterSelectionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCharacterSelectionElement: {
        prototype: HTMLCharacterSelectionElement;
        new (): HTMLCharacterSelectionElement;
    };
    interface HTMLConsoleAboutElementEventMap {
        "console.logged": Log;
    }
    interface HTMLConsoleAboutElement extends Components.ConsoleAbout, HTMLStencilElement {
        addEventListener<K extends keyof HTMLConsoleAboutElementEventMap>(type: K, listener: (this: HTMLConsoleAboutElement, ev: ConsoleAboutCustomEvent<HTMLConsoleAboutElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLConsoleAboutElementEventMap>(type: K, listener: (this: HTMLConsoleAboutElement, ev: ConsoleAboutCustomEvent<HTMLConsoleAboutElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLConsoleAboutElement: {
        prototype: HTMLConsoleAboutElement;
        new (): HTMLConsoleAboutElement;
    };
    interface HTMLConsoleWelcomeElement extends Components.ConsoleWelcome, HTMLStencilElement {
    }
    var HTMLConsoleWelcomeElement: {
        prototype: HTMLConsoleWelcomeElement;
        new (): HTMLConsoleWelcomeElement;
    };
    interface HTMLDropdownButtonElement extends Components.DropdownButton, HTMLStencilElement {
    }
    var HTMLDropdownButtonElement: {
        prototype: HTMLDropdownButtonElement;
        new (): HTMLDropdownButtonElement;
    };
    interface HTMLFruitItemElement extends Components.FruitItem, HTMLStencilElement {
    }
    var HTMLFruitItemElement: {
        prototype: HTMLFruitItemElement;
        new (): HTMLFruitItemElement;
    };
    interface HTMLFruitTreeElement extends Components.FruitTree, HTMLStencilElement {
    }
    var HTMLFruitTreeElement: {
        prototype: HTMLFruitTreeElement;
        new (): HTMLFruitTreeElement;
    };
    interface HTMLGui404ElementEventMap {
        "console.logged": Log;
    }
    interface HTMLGui404Element extends Components.Gui404, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGui404ElementEventMap>(type: K, listener: (this: HTMLGui404Element, ev: Gui404CustomEvent<HTMLGui404ElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGui404ElementEventMap>(type: K, listener: (this: HTMLGui404Element, ev: Gui404CustomEvent<HTMLGui404ElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGui404Element: {
        prototype: HTMLGui404Element;
        new (): HTMLGui404Element;
    };
    interface HTMLGuiAboutElement extends Components.GuiAbout, HTMLStencilElement {
    }
    var HTMLGuiAboutElement: {
        prototype: HTMLGuiAboutElement;
        new (): HTMLGuiAboutElement;
    };
    interface HTMLGuiBlogElement extends Components.GuiBlog, HTMLStencilElement {
    }
    var HTMLGuiBlogElement: {
        prototype: HTMLGuiBlogElement;
        new (): HTMLGuiBlogElement;
    };
    interface HTMLGuiProjectsElement extends Components.GuiProjects, HTMLStencilElement {
    }
    var HTMLGuiProjectsElement: {
        prototype: HTMLGuiProjectsElement;
        new (): HTMLGuiProjectsElement;
    };
    interface HTMLGuiWelcomeElementEventMap {
        "pull.box.up": boolean;
        "console.logged": Log;
    }
    interface HTMLGuiWelcomeElement extends Components.GuiWelcome, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGuiWelcomeElementEventMap>(type: K, listener: (this: HTMLGuiWelcomeElement, ev: GuiWelcomeCustomEvent<HTMLGuiWelcomeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGuiWelcomeElementEventMap>(type: K, listener: (this: HTMLGuiWelcomeElement, ev: GuiWelcomeCustomEvent<HTMLGuiWelcomeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGuiWelcomeElement: {
        prototype: HTMLGuiWelcomeElement;
        new (): HTMLGuiWelcomeElement;
    };
    interface HTMLLanguageSelectorElement extends Components.LanguageSelector, HTMLStencilElement {
    }
    var HTMLLanguageSelectorElement: {
        prototype: HTMLLanguageSelectorElement;
        new (): HTMLLanguageSelectorElement;
    };
    interface HTMLLoadingModalElementEventMap {
        "toggle.volume": void;
    }
    interface HTMLLoadingModalElement extends Components.LoadingModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLoadingModalElementEventMap>(type: K, listener: (this: HTMLLoadingModalElement, ev: LoadingModalCustomEvent<HTMLLoadingModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLoadingModalElementEventMap>(type: K, listener: (this: HTMLLoadingModalElement, ev: LoadingModalCustomEvent<HTMLLoadingModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLoadingModalElement: {
        prototype: HTMLLoadingModalElement;
        new (): HTMLLoadingModalElement;
    };
    interface HTMLLogoTextElement extends Components.LogoText, HTMLStencilElement {
    }
    var HTMLLogoTextElement: {
        prototype: HTMLLogoTextElement;
        new (): HTMLLogoTextElement;
    };
    interface HTMLMainFooterElement extends Components.MainFooter, HTMLStencilElement {
    }
    var HTMLMainFooterElement: {
        prototype: HTMLMainFooterElement;
        new (): HTMLMainFooterElement;
    };
    interface HTMLMainHeaderElementEventMap {
        "pull.box.up": boolean;
        "console.logged": Log;
        "toggle.menu": void;
        "toggle.volume": void;
    }
    interface HTMLMainHeaderElement extends Components.MainHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMainHeaderElementEventMap>(type: K, listener: (this: HTMLMainHeaderElement, ev: MainHeaderCustomEvent<HTMLMainHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMainHeaderElementEventMap>(type: K, listener: (this: HTMLMainHeaderElement, ev: MainHeaderCustomEvent<HTMLMainHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMainHeaderElement: {
        prototype: HTMLMainHeaderElement;
        new (): HTMLMainHeaderElement;
    };
    interface HTMLMessageBubbleElement extends Components.MessageBubble, HTMLStencilElement {
    }
    var HTMLMessageBubbleElement: {
        prototype: HTMLMessageBubbleElement;
        new (): HTMLMessageBubbleElement;
    };
    interface HTMLModalBackdropElementEventMap {
        "console.logged": Log;
    }
    interface HTMLModalBackdropElement extends Components.ModalBackdrop, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModalBackdropElementEventMap>(type: K, listener: (this: HTMLModalBackdropElement, ev: ModalBackdropCustomEvent<HTMLModalBackdropElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModalBackdropElementEventMap>(type: K, listener: (this: HTMLModalBackdropElement, ev: ModalBackdropCustomEvent<HTMLModalBackdropElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModalBackdropElement: {
        prototype: HTMLModalBackdropElement;
        new (): HTMLModalBackdropElement;
    };
    interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {
    }
    var HTMLPageNotFoundElement: {
        prototype: HTMLPageNotFoundElement;
        new (): HTMLPageNotFoundElement;
    };
    interface HTMLPwaInstallPromptElement extends Components.PwaInstallPrompt, HTMLStencilElement {
    }
    var HTMLPwaInstallPromptElement: {
        prototype: HTMLPwaInstallPromptElement;
        new (): HTMLPwaInstallPromptElement;
    };
    interface HTMLRightPanelElementEventMap {
        "menu.opened": Partial<BackDropOptions> | undefined;
        "menu.closed": Partial<BackDropOptions> | undefined;
        "menu.resizing.start": string;
        "menu.resizing": [string, number];
        "menu.resized": string;
    }
    interface HTMLRightPanelElement extends Components.RightPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRightPanelElementEventMap>(type: K, listener: (this: HTMLRightPanelElement, ev: RightPanelCustomEvent<HTMLRightPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRightPanelElementEventMap>(type: K, listener: (this: HTMLRightPanelElement, ev: RightPanelCustomEvent<HTMLRightPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRightPanelElement: {
        prototype: HTMLRightPanelElement;
        new (): HTMLRightPanelElement;
    };
    interface HTMLSimpleLinkElementEventMap {
        "state.pushed": { state: any; title: string; url?: string | URL | null; };
    }
    interface HTMLSimpleLinkElement extends Components.SimpleLink, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSimpleLinkElementEventMap>(type: K, listener: (this: HTMLSimpleLinkElement, ev: SimpleLinkCustomEvent<HTMLSimpleLinkElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSimpleLinkElementEventMap>(type: K, listener: (this: HTMLSimpleLinkElement, ev: SimpleLinkCustomEvent<HTMLSimpleLinkElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSimpleLinkElement: {
        prototype: HTMLSimpleLinkElement;
        new (): HTMLSimpleLinkElement;
    };
    interface HTMLSkeletonLoaderElement extends Components.SkeletonLoader, HTMLStencilElement {
    }
    var HTMLSkeletonLoaderElement: {
        prototype: HTMLSkeletonLoaderElement;
        new (): HTMLSkeletonLoaderElement;
    };
    interface HTMLSocialLinksElement extends Components.SocialLinks, HTMLStencilElement {
    }
    var HTMLSocialLinksElement: {
        prototype: HTMLSocialLinksElement;
        new (): HTMLSocialLinksElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "background-activity": HTMLBackgroundActivityElement;
        "character-selection": HTMLCharacterSelectionElement;
        "console-about": HTMLConsoleAboutElement;
        "console-welcome": HTMLConsoleWelcomeElement;
        "dropdown-button": HTMLDropdownButtonElement;
        "fruit-item": HTMLFruitItemElement;
        "fruit-tree": HTMLFruitTreeElement;
        "gui-404": HTMLGui404Element;
        "gui-about": HTMLGuiAboutElement;
        "gui-blog": HTMLGuiBlogElement;
        "gui-projects": HTMLGuiProjectsElement;
        "gui-welcome": HTMLGuiWelcomeElement;
        "language-selector": HTMLLanguageSelectorElement;
        "loading-modal": HTMLLoadingModalElement;
        "logo-text": HTMLLogoTextElement;
        "main-footer": HTMLMainFooterElement;
        "main-header": HTMLMainHeaderElement;
        "message-bubble": HTMLMessageBubbleElement;
        "modal-backdrop": HTMLModalBackdropElement;
        "page-not-found": HTMLPageNotFoundElement;
        "pwa-install-prompt": HTMLPwaInstallPromptElement;
        "right-panel": HTMLRightPanelElement;
        "simple-link": HTMLSimpleLinkElement;
        "skeleton-loader": HTMLSkeletonLoaderElement;
        "social-links": HTMLSocialLinksElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    /**
     * -  TODO aria
     * -  TODO first page + 404page links to back & home
     * -  TODO modals :  Upcoming features
     * -  TODO translate: FR, ES, EN, HT
     * - TODO settings menu : Language , resolution, FPS ...
     * - TODO Test new fonts:  Monument Grotesk
     * - TODO Add sound in open and close menu, change link...
     * - TODO Add my picture+ name
     */
    interface AppRoot {
        "onConsole.logged"?: (event: AppRootCustomEvent<Log>) => void;
        "onLanguage.changed"?: (event: AppRootCustomEvent<Language>) => void;
        "onRedraw.screen"?: (event: AppRootCustomEvent<boolean>) => void;
        "onState.pushed"?: (event: AppRootCustomEvent<{ state: any; title: string; url?: string | URL | null; }>) => void;
    }
    interface BackgroundActivity {
        /**
          * @default ''
         */
        "digiCode"?: string;
        "menuWidth": number;
    }
    interface CharacterSelection {
        "onClose.loading"?: (event: CharacterSelectionCustomEvent<boolean>) => void;
    }
    interface ConsoleAbout {
        "onConsole.logged"?: (event: ConsoleAboutCustomEvent<Log>) => void;
    }
    interface ConsoleWelcome {
    }
    interface DropdownButton {
        /**
          * @default {}
         */
        "options"?: Partial<OptionConfig>;
    }
    interface FruitItem {
        /**
          * @default false
         */
        "crystal"?: boolean;
        /**
          * @default 0
         */
        "flavor"?: number;
        /**
          * @default 0
         */
        "type"?: number;
    }
    interface FruitTree {
        /**
          * @default false
         */
        "debug"?: boolean;
        /**
          * @default 'inherit'
         */
        "filter"?: string;
        /**
          * @default 0
         */
        "fruit"?: number;
        /**
          * @default 16
         */
        "fruitSize"?: number;
        /**
          * @default '../../assets/images/tree.png'
         */
        "image"?: string;
        /**
          * @default 8
         */
        "numberOfFruits"?: number;
        /**
          * @default DEFAULT_FOLIAGE_RATIOS
         */
        "ratios"?: FoliageRatio;
        /**
          * @default 1
         */
        "scale"?: number;
        /**
          * @default 'inherit'
         */
        "transform"?: string;
    }
    interface Gui404 {
        "onConsole.logged"?: (event: Gui404CustomEvent<Log>) => void;
    }
    interface GuiAbout {
        "hash": string | undefined;
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface GuiBlog {
        "hash": string;
        /**
          * @default true
         */
        "menuOpened"?: boolean;
        "menuWidth": number;
    }
    interface GuiProjects {
        "hash": string;
        /**
          * @default true
         */
        "menuOpened"?: boolean;
        "menuWidth": number;
    }
    interface GuiWelcome {
        "menuOpened": boolean;
        "menuWidth": number;
        "onConsole.logged"?: (event: GuiWelcomeCustomEvent<Log>) => void;
        "onPull.box.up"?: (event: GuiWelcomeCustomEvent<boolean>) => void;
        "player": Nullable<Player>;
    }
    interface LanguageSelector {
    }
    interface LoadingModal {
        "onToggle.volume"?: (event: LoadingModalCustomEvent<void>) => void;
        "player"?: Nullable<Player>;
        "progress": number;
        "progressText": string;
        "volumeMuted": boolean;
    }
    interface LogoText {
    }
    interface MainFooter {
        "menuOpened": boolean;
        "menuWidth": number;
    }
    interface MainHeader {
        "menuOpened": boolean;
        "menuWidth": number;
        "message"?: {
    text?: string;
    content?: string
  };
        "onConsole.logged"?: (event: MainHeaderCustomEvent<Log>) => void;
        "onPull.box.up"?: (event: MainHeaderCustomEvent<boolean>) => void;
        "onToggle.menu"?: (event: MainHeaderCustomEvent<void>) => void;
        "onToggle.volume"?: (event: MainHeaderCustomEvent<void>) => void;
        "player"?: Nullable<Player>;
        "volumeMuted": boolean;
    }
    interface MessageBubble {
        "character"?: Nullable<HTMLElement>;
        "message"?: string;
    }
    interface ModalBackdrop {
        "onConsole.logged"?: (event: ModalBackdropCustomEvent<Log>) => void;
    }
    interface PageNotFound {
    }
    interface PwaInstallPrompt {
    }
    interface RightPanel {
        "isOpened"?: boolean;
        "onMenu.closed"?: (event: RightPanelCustomEvent<Partial<BackDropOptions> | undefined>) => void;
        "onMenu.opened"?: (event: RightPanelCustomEvent<Partial<BackDropOptions> | undefined>) => void;
        "onMenu.resized"?: (event: RightPanelCustomEvent<string>) => void;
        "onMenu.resizing"?: (event: RightPanelCustomEvent<[string, number]>) => void;
        "onMenu.resizing.start"?: (event: RightPanelCustomEvent<string>) => void;
    }
    interface SimpleLink {
        /**
          * @default 'FruitsBytes'
         */
        "label"?: string;
        /**
          * @default '/welcome#'
         */
        "link"?: string;
        "onState.pushed"?: (event: SimpleLinkCustomEvent<{ state: any; title: string; url?: string | URL | null; }>) => void;
        /**
          * @default {}
         */
        "state"?: Object;
    }
    interface SkeletonLoader {
        /**
          * @default true
         */
        "animated"?: boolean;
        /**
          * @default 1
         */
        "count"?: number;
        /**
          * @default '20px'
         */
        "height"?: string;
        /**
          * @default 'text'
         */
        "type"?: SkeletonType;
        /**
          * @default '100%'
         */
        "width"?: string;
    }
    interface SocialLinks {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "background-activity": BackgroundActivity;
        "character-selection": CharacterSelection;
        "console-about": ConsoleAbout;
        "console-welcome": ConsoleWelcome;
        "dropdown-button": DropdownButton;
        "fruit-item": FruitItem;
        "fruit-tree": FruitTree;
        "gui-404": Gui404;
        "gui-about": GuiAbout;
        "gui-blog": GuiBlog;
        "gui-projects": GuiProjects;
        "gui-welcome": GuiWelcome;
        "language-selector": LanguageSelector;
        "loading-modal": LoadingModal;
        "logo-text": LogoText;
        "main-footer": MainFooter;
        "main-header": MainHeader;
        "message-bubble": MessageBubble;
        "modal-backdrop": ModalBackdrop;
        "page-not-found": PageNotFound;
        "pwa-install-prompt": PwaInstallPrompt;
        "right-panel": RightPanel;
        "simple-link": SimpleLink;
        "skeleton-loader": SkeletonLoader;
        "social-links": SocialLinks;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            /**
             * -  TODO aria
             * -  TODO first page + 404page links to back & home
             * -  TODO modals :  Upcoming features
             * -  TODO translate: FR, ES, EN, HT
             * - TODO settings menu : Language , resolution, FPS ...
             * - TODO Test new fonts:  Monument Grotesk
             * - TODO Add sound in open and close menu, change link...
             * - TODO Add my picture+ name
             */
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "background-activity": LocalJSX.BackgroundActivity & JSXBase.HTMLAttributes<HTMLBackgroundActivityElement>;
            "character-selection": LocalJSX.CharacterSelection & JSXBase.HTMLAttributes<HTMLCharacterSelectionElement>;
            "console-about": LocalJSX.ConsoleAbout & JSXBase.HTMLAttributes<HTMLConsoleAboutElement>;
            "console-welcome": LocalJSX.ConsoleWelcome & JSXBase.HTMLAttributes<HTMLConsoleWelcomeElement>;
            "dropdown-button": LocalJSX.DropdownButton & JSXBase.HTMLAttributes<HTMLDropdownButtonElement>;
            "fruit-item": LocalJSX.FruitItem & JSXBase.HTMLAttributes<HTMLFruitItemElement>;
            "fruit-tree": LocalJSX.FruitTree & JSXBase.HTMLAttributes<HTMLFruitTreeElement>;
            "gui-404": LocalJSX.Gui404 & JSXBase.HTMLAttributes<HTMLGui404Element>;
            "gui-about": LocalJSX.GuiAbout & JSXBase.HTMLAttributes<HTMLGuiAboutElement>;
            "gui-blog": LocalJSX.GuiBlog & JSXBase.HTMLAttributes<HTMLGuiBlogElement>;
            "gui-projects": LocalJSX.GuiProjects & JSXBase.HTMLAttributes<HTMLGuiProjectsElement>;
            "gui-welcome": LocalJSX.GuiWelcome & JSXBase.HTMLAttributes<HTMLGuiWelcomeElement>;
            "language-selector": LocalJSX.LanguageSelector & JSXBase.HTMLAttributes<HTMLLanguageSelectorElement>;
            "loading-modal": LocalJSX.LoadingModal & JSXBase.HTMLAttributes<HTMLLoadingModalElement>;
            "logo-text": LocalJSX.LogoText & JSXBase.HTMLAttributes<HTMLLogoTextElement>;
            "main-footer": LocalJSX.MainFooter & JSXBase.HTMLAttributes<HTMLMainFooterElement>;
            "main-header": LocalJSX.MainHeader & JSXBase.HTMLAttributes<HTMLMainHeaderElement>;
            "message-bubble": LocalJSX.MessageBubble & JSXBase.HTMLAttributes<HTMLMessageBubbleElement>;
            "modal-backdrop": LocalJSX.ModalBackdrop & JSXBase.HTMLAttributes<HTMLModalBackdropElement>;
            "page-not-found": LocalJSX.PageNotFound & JSXBase.HTMLAttributes<HTMLPageNotFoundElement>;
            "pwa-install-prompt": LocalJSX.PwaInstallPrompt & JSXBase.HTMLAttributes<HTMLPwaInstallPromptElement>;
            "right-panel": LocalJSX.RightPanel & JSXBase.HTMLAttributes<HTMLRightPanelElement>;
            "simple-link": LocalJSX.SimpleLink & JSXBase.HTMLAttributes<HTMLSimpleLinkElement>;
            "skeleton-loader": LocalJSX.SkeletonLoader & JSXBase.HTMLAttributes<HTMLSkeletonLoaderElement>;
            "social-links": LocalJSX.SocialLinks & JSXBase.HTMLAttributes<HTMLSocialLinksElement>;
        }
    }
}
